### PR TITLE
Change the filter strings to plural

### PR DESCRIPTION
**Pull request by ayamdobhal**
Cause zeroinfinity wanted that XD. And it made sense

### CODE REVIEW

**Comment by gotenksIN** [comment]
@AyamDobhal Ok

**Comment by skittles9823** [comment]
Change
```
audios
```
Back to
```
audio
```

**Comment by ayamdobhal** [comment]
@skittles9823 Done

**Comment by yash-garg** [comment]
@AyamDobhal Ooo

**Comment by yash-garg** [comment]
***MERGEEEEEEEEEEEE EEEEEEEEETT***

**Comment by SphericalKat** [comment]
@Yash-Garg Nu

**Comment by gotenksIN** [comment]
@Yash-Garg Me lazy to test reeeeeeeeee

**Comment by yash-garg** [comment]
U **gendu** @songotenks69

**Comment by SphericalKat** [comment]
@Yash-Garg Nou

**Comment by skittles9823** [comment]
@songotenks69 You literally asked for this to be pr'd to OC specifically for you to test it. Smh.

**Comment by yash-garg** [comment]
NoU SphericalFlyingHair

**Comment by SphericalKat** [comment]
@Yash-Garg I'm hot and you're just jealous

**Comment by yash-garg** [comment]
You're dumb and we are just accepting the fact @ATechnoHazard

**Comment by gotenksIN** [comment]
@skittles9823 I am sick and mom isn't giving me much time go figure

**Comment by yash-garg** [comment]
RIP @songotenks69

**Pull request merged**
